name: TabPrefix
main: me.snowsun.tabprefix.TabPrefix
version: 2.0.0
api-version: 1.16
depend: [LuckPerms]
commands:
  lptab:
    description: TabPrefix main command
    usage: /lptab <reload|localadjust|approvechanges <code>>
  certhelp:
    description: Certificate trust instructions
  certexport:
    description: Export generated certificate (admin)
permissions:
  tabprefix.reload:
    default: op
  tabprefix.adjust:
    default: op
  tabprefix.approve:
    default: op
